#!/usr/bin/env python3
r"""
The netplan document, checked in both languages, in seconds and without a VM.

    ./check-netplan-rule.py                          PowerShell half only
    ./check-netplan-rule.py --setup <os7-setup>      both halves
    ./check-netplan-rule.py --docker os7-build:amd64 both halves, off Linux

WHY IT EXISTS. The netplan document is generated TWICE: in C# by
`NetworkPlan.ToNetplanYaml` (installer/src/OS7.Setup/Model/NetworkPlan.cs), which
is what `os7-setup` writes during an install, and in PowerShell by
`New-NetplanDocument` (powershell/Net/Net.psm1), which is what the OS/7 cmdlets
will write on a running machine. Two implementations of one specification, in
two languages, each maintained by whoever is editing that side.

That is BUILD-NOTES #66 waiting to happen — code that replaces a spike must be
DIFFED against it, and a paraphrase written from the same notes takes a
different route. The failure mode is the worst one this subsystem has: netplan
accepts a document that matches no hardware, brings nothing up, and reports
NOTHING. No address, no route, no error, and on a headless machine that is a
site visit (L28, measured 2026-08-25).

docs/POWERSHELL-SURFACE-PLAN.md P3 is the two-step plan for having one renderer
instead of two. Until step 2 runs — it needs the Apple Silicon host, because
`run-phase3.py all` is its gate — this file is what keeps the two honest.

SO THE CASES BELOW ARE THE SPECIFICATION. They live here and nowhere else, and
each implementation is checked against THEM, byte for byte, before the two are
compared with each other. Checking the two against each other alone would pass
on the day they drift together — the same argument check-version-rule.py makes
in its own header, for the same reason.

THE C# HALF NEEDS A RUNNABLE `os7-setup`, which is a Linux binary. On macOS and
Windows there is nothing to execute, so that half is REPORTED AS NOT CHECKED
rather than skipped quietly or counted as a pass. "Cannot tell" is not "clean".

    docker run --rm --platform linux/amd64 -v "$PWD":/work os7-build:amd64 bash -c \
      'cd /work/installer/src/OS7.Setup && dotnet publish -c Release -r linux-x64 \
       -p:PublishAot=true -o /tmp/pub && cp /tmp/pub/os7-setup /work/out/'
"""
import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
MODULE = os.path.join(REPO, "powershell", "Net", "Net.psd1")

# ---------------------------------------------------------------------------
# THE SPECIFICATION.
#
# Each case is (name, input, expected document). The input is the same dict for
# both languages; each side maps it onto its own parameter names, and that
# mapping is the only thing either side is allowed to do differently.
#
# The expected document is written out IN FULL rather than as a list of
# substrings. `--self-test` on the C# side checks substrings, and substrings
# cannot see an extra line, a wrong indent or a key emitted twice — all three of
# which netplan reads as something, and none of which it complains about.
# ---------------------------------------------------------------------------

HEADER = r"""# Written by OS/7 Setup selftest.
#
# Regenerated by Setup on every install. Edit freely afterwards -
# nothing in OS/7 rewrites this file after the machine is installed.
network:
  version: 2
"""

DHCP = r"""      dhcp4: true
      dhcp6: true
      accept-ra: true
"""

CASES = [
    (
        "DHCP over Ethernet, named interface",
        {"iface": "enp1s0", "method": "dhcp"},
        HEADER + "  renderer: networkd\n  ethernets:\n    enp1s0:\n" + DHCP,
    ),
    (
        # D14, and L24 is what getting it wrong costs. The renderer is a
        # parameter on both sides and derived on neither.
        "the renderer is whatever it is handed",
        {"iface": "enp1s0", "method": "dhcp", "renderer": "NetworkManager"},
        HEADER + "  renderer: NetworkManager\n  ethernets:\n    enp1s0:\n" + DHCP,
    ),
    (
        # L30, AND THE MOST EXPENSIVE THING PHASE 3b LEARNED. One machine, one
        # NIC: enp0s5 while installing, enp0s2 once booted, because the setup
        # medium is a PCI device and removing it renumbers the slots. The name
        # Setup sees is NOT the name the installed machine uses.
        "a chosen adapter is matched by MAC, and the block is labelled os7net",
        {"iface": "enp0s5", "mac": "52:54:00:12:34:56", "method": "dhcp"},
        HEADER + "  renderer: networkd\n  ethernets:\n    os7net:\n"
        + "      match:\n        macaddress: \"52:54:00:12:34:56\"\n" + DHCP,
    ),
    (
        "a MAC is lower-cased, because that is what netplan matches",
        {"iface": "eth0", "mac": "AA:BB:CC:DD:EE:FF", "method": "dhcp"},
        HEADER + "  renderer: networkd\n  ethernets:\n    os7net:\n"
        + "      match:\n        macaddress: \"aa:bb:cc:dd:ee:ff\"\n" + DHCP,
    ),
    (
        # L28: a plan replayed on another machine must not carry this machine's
        # interface name.
        "interface 'auto' becomes a wired match glob",
        {"iface": "auto", "method": "dhcp"},
        HEADER + "  renderer: networkd\n  ethernets:\n    os7net:\n"
        + "      match:\n        name: \"en*\"\n" + DHCP,
    ),
    (
        "interface 'auto' on a wireless link globs wl*, not en*",
        {"iface": "auto", "kind": "wireless", "method": "dhcp",
         "ssid": "Roaming", "psk": "passphrase"},
        HEADER + "  renderer: networkd\n  wifis:\n    os7net:\n"
        + "      match:\n        name: \"wl*\"\n" + DHCP
        + "      access-points:\n        \"Roaming\":\n          auth:\n"
        + "            key-management: psk\n            password: \"passphrase\"\n",
    ),
    (
        # A plan that carries a MAC is describing a specific port; `auto` is for
        # hardware the writer has never seen. The specific one wins.
        "a MAC in the plan beats the 'auto' glob",
        {"iface": "auto", "mac": "aa:bb:cc:dd:ee:ff", "method": "dhcp"},
        HEADER + "  renderer: networkd\n  ethernets:\n    os7net:\n"
        + "      match:\n        macaddress: \"aa:bb:cc:dd:ee:ff\"\n" + DHCP,
    ),
    (
        # `routes:`, never `gateway4:` — netplan deprecated it and warns into a
        # log nobody on a headless machine reads.
        "static address, gateway, DNS and a search domain",
        {"iface": "enp1s0", "method": "static", "address": "10.0.2.99/24",
         "gateway": "10.0.2.2", "dns": "10.0.2.3", "search": "corp.example.com"},
        HEADER + "  renderer: networkd\n  ethernets:\n    enp1s0:\n"
        + "      dhcp4: false\n      dhcp6: false\n"
        + "      addresses:\n        - 10.0.2.99/24\n"
        + "      routes:\n        - to: default\n          via: 10.0.2.2\n"
        + "      nameservers:\n        addresses:\n          - 10.0.2.3\n"
        + "        search:\n          - \"corp.example.com\"\n",
    ),
    (
        # A segment with no route off it is a real thing, and refusing to render
        # without a gateway would be inventing a requirement the network has not
        # got.
        "a static address with no gateway emits no routes block",
        {"iface": "enp1s0", "method": "static", "address": "192.168.5.4/24"},
        HEADER + "  renderer: networkd\n  ethernets:\n    enp1s0:\n"
        + "      dhcp4: false\n      dhcp6: false\n"
        + "      addresses:\n        - 192.168.5.4/24\n",
    ),
    (
        "several nameservers and several search domains, in order",
        {"iface": "enp1s0", "method": "static", "address": "10.0.0.5/8",
         "dns": "10.0.0.1,10.0.0.2,10.0.0.3",
         "search": "corp.example.com,ad.example.com"},
        HEADER + "  renderer: networkd\n  ethernets:\n    enp1s0:\n"
        + "      dhcp4: false\n      dhcp6: false\n"
        + "      addresses:\n        - 10.0.0.5/8\n"
        + "      nameservers:\n        addresses:\n"
        + "          - 10.0.0.1\n          - 10.0.0.2\n          - 10.0.0.3\n"
        + "        search:\n          - \"corp.example.com\"\n          - \"ad.example.com\"\n",
    ),
    (
        "WPA2 personal",
        {"iface": "wlp2s0", "kind": "wireless", "method": "dhcp",
         "ssid": "Branch-Office", "psk": "hunter2hunter2"},
        HEADER + "  renderer: networkd\n  wifis:\n    wlp2s0:\n" + DHCP
        + "      access-points:\n        \"Branch-Office\":\n          auth:\n"
        + "            key-management: psk\n            password: \"hunter2hunter2\"\n",
    ),
    (
        # `hidden:` changes the scan technique rather than being cosmetic, and it
        # sits between the SSID and `auth:` — an ordering neither side may drift
        # on, because netplan reads the block as a mapping and a human reads it
        # as a diff.
        "a hidden network",
        {"iface": "wlp2s0", "kind": "wireless", "method": "dhcp",
         "ssid": "NotBroadcast", "psk": "passphrase", "hidden": "true"},
        HEADER + "  renderer: networkd\n  wifis:\n    wlp2s0:\n" + DHCP
        + "      access-points:\n        \"NotBroadcast\":\n          hidden: true\n"
        + "          auth:\n"
        + "            key-management: psk\n            password: \"passphrase\"\n",
    ),
    (
        "802.1X PEAP/MSCHAPv2 with a CA certificate",
        {"iface": "wlp2s0", "kind": "wireless", "method": "dhcp",
         "ssid": "CORP-SECURE", "security": "enterprise",
         "identity": "user@corp.example.com", "password": "s3cret",
         "cacert": "/run/media/ca.pem"},
        HEADER + "  renderer: networkd\n  wifis:\n    wlp2s0:\n" + DHCP
        + "      access-points:\n        \"CORP-SECURE\":\n          auth:\n"
        + "            key-management: eap\n            method: peap\n"
        + "            identity: \"user@corp.example.com\"\n"
        + "            password: \"s3cret\"\n            phase2-auth: MSCHAPV2\n"
        + "            ca-certificate: \"/run/media/ca.pem\"\n",
    ),
    (
        # L27: blank is legal and means the RADIUS server is not verified, which
        # screen 9W prints rather than defaulting to silently. The document must
        # then carry NO ca-certificate key at all rather than an empty one.
        "802.1X with an anonymous identity and no CA certificate",
        {"iface": "wlp2s0", "kind": "wireless", "method": "dhcp",
         "ssid": "CORP-SECURE", "security": "enterprise",
         "identity": "user@corp.example.com", "anonymous": "anonymous@example.com",
         "password": "s3cret"},
        HEADER + "  renderer: networkd\n  wifis:\n    wlp2s0:\n" + DHCP
        + "      access-points:\n        \"CORP-SECURE\":\n          auth:\n"
        + "            key-management: eap\n            method: peap\n"
        + "            identity: \"user@corp.example.com\"\n"
        + "            anonymous-identity: \"anonymous@example.com\"\n"
        + "            password: \"s3cret\"\n            phase2-auth: MSCHAPV2\n",
    ),
    (
        # A CA certificate is meaningless on a PSK network, and the C# renderer
        # returns before it could emit one. What a generator does NOT write is
        # part of the specification too.
        "a CA certificate on a PSK network is not written",
        {"iface": "wlp2s0", "kind": "wireless", "method": "dhcp",
         "ssid": "Branch-Office", "psk": "hunter2hunter2",
         "cacert": "/run/media/ca.pem"},
        HEADER + "  renderer: networkd\n  wifis:\n    wlp2s0:\n" + DHCP
        + "      access-points:\n        \"Branch-Office\":\n          auth:\n"
        + "            key-management: psk\n            password: \"hunter2hunter2\"\n",
    ),
    (
        # An SSID is arbitrary bytes. A colon, a `#`, a leading `-` or a quote
        # each change what an unquoted YAML line means, and the result is a file
        # netplan either misreads or refuses.
        "an SSID with quotes, a colon and a hash is escaped",
        {"iface": "wlp2s0", "kind": "wireless", "method": "dhcp",
         "ssid": "we: \"guest\" #1", "psk": "passphrase"},
        HEADER + "  renderer: networkd\n  wifis:\n    wlp2s0:\n" + DHCP
        + "      access-points:\n        \"we: \\\"guest\\\" #1\":\n          auth:\n"
        + "            key-management: psk\n            password: \"passphrase\"\n",
    ),
    (
        # The backslash pass has to run BEFORE the quote pass, or the backslash
        # the quote pass adds gets escaped by the backslash pass. Both languages
        # get this wrong the same way if written carelessly, which is exactly why
        # it is a case and not a comment.
        "a backslash in a passphrase survives, escaped once",
        {"iface": "wlp2s0", "kind": "wireless", "method": "dhcp",
         "ssid": "Site", "psk": "pass\\word"},
        HEADER + "  renderer: networkd\n  wifis:\n    wlp2s0:\n" + DHCP
        + "      access-points:\n        \"Site\":\n          auth:\n"
        + "            key-management: psk\n            password: \"pass\\\\word\"\n",
    ),
]

# `None` is a real choice (L23) and it is spelled by writing NO FILE. A caller
# that renders it anyway writes an empty block, which netplan accepts and which
# configures nothing — so both sides must refuse rather than produce something.
REFUSAL = {"iface": "enp1s0", "method": "none"}

FAILS = []


def check(ok, what, detail=""):
    print(f"      {'ok  ' if ok else 'FAIL'}  {what}" + (f"   [{detail}]" if detail else ""))
    if not ok:
        FAILS.append(what)
    return ok


def show_diff(want, got):
    """The first line that differs, with both sides quoted.

    Byte-exact comparison with no diff is a check that says "no" and nothing
    else, and this file exists precisely for the case where somebody has to fix
    one of two renderers.
    """
    w = want.decode("utf-8", "replace").splitlines()
    g = got.decode("utf-8", "replace").splitlines()
    for i in range(max(len(w), len(g))):
        a = w[i] if i < len(w) else "<end of document>"
        b = g[i] if i < len(g) else "<end of document>"
        if a != b:
            print(f"            line {i + 1}")
            print(f"              want: {a!r}")
            print(f"              got:  {b!r}")
            return
    print(f"            same lines, different bytes: {len(want)} want, {len(got)} got")


# ---------------------------------------------------------------------------
# 1. The rule, in PowerShell — through powershell/Net
# ---------------------------------------------------------------------------

def pwsh():
    exe = shutil.which("pwsh")
    if not exe:
        sys.exit("pwsh not found; this check runs the real powershell/Net module.")
    return exe


# The case reaches PowerShell as JSON in a file and the document comes back as
# BYTES in a file. Neither goes through a console: pwsh's stdout is a TextWriter
# with a host-dependent encoding and newline policy, and a byte-exact check that
# reads its own answer through one is checking the console as much as the rule.
PS_DRIVER = r"""
$ErrorActionPreference = 'Stop'
Import-Module '{module}' -Force
$c = Get-Content -Raw -LiteralPath '{casefile}' | ConvertFrom-Json -AsHashtable

$a = @{{
    Renderer = if ($c.ContainsKey('renderer')) {{ $c.renderer }} else {{ 'networkd' }}
    Version  = if ($c.ContainsKey('version'))  {{ $c.version  }} else {{ 'selftest' }}
    Method   = (Get-Culture).TextInfo.ToTitleCase($c.method)
}}
if ($c.ContainsKey('iface'))    {{ $a.InterfaceName = $c.iface }}
if ($c.ContainsKey('mac'))      {{ $a.MacAddress    = $c.mac }}
if ($c.ContainsKey('address'))  {{ $a.Address       = $c.address }}
if ($c.ContainsKey('gateway'))  {{ $a.Gateway       = $c.gateway }}
if ($c.ContainsKey('dns'))      {{ $a.Nameserver    = $c.dns    -split ',' }}
if ($c.ContainsKey('search'))   {{ $a.SearchDomain  = $c.search -split ',' }}
if ($c.ContainsKey('kind') -and $c.kind -eq 'wireless') {{ $a.Wireless = $true }}
if ($c.ContainsKey('ssid'))     {{ $a.Ssid          = $c.ssid }}
if ($c.ContainsKey('hidden') -and $c.hidden -eq 'true') {{ $a.Hidden = $true }}
if ($c.ContainsKey('security')) {{
    $a.Security = (Get-Culture).TextInfo.ToTitleCase($c.security)
}}
if ($c.ContainsKey('identity'))  {{ $a.Identity          = $c.identity }}
if ($c.ContainsKey('anonymous')) {{ $a.AnonymousIdentity = $c.anonymous }}
if ($c.ContainsKey('cacert'))    {{ $a.CaCertificate     = $c.cacert }}
# P7: a secret is a [securestring] at every boundary, including a test's.
if ($c.ContainsKey('psk')) {{
    $a.Psk = ConvertTo-SecureString $c.psk -AsPlainText -Force
}}
if ($c.ContainsKey('password')) {{
    $a.Password = ConvertTo-SecureString $c.password -AsPlainText -Force
}}

try {{
    $doc = New-NetplanDocument @a
}} catch [System.InvalidOperationException] {{
    [System.IO.File]::WriteAllBytes('{outfile}', [byte[]]@())
    exit 3
}}
[System.IO.File]::WriteAllBytes('{outfile}',
    [System.Text.Encoding]::UTF8.GetBytes($doc))
"""


def powershell_render(lab, case, n):
    casefile = os.path.join(lab, f"case{n}.json")
    outfile = os.path.join(lab, f"case{n}.yaml")
    with open(casefile, "w", encoding="utf-8") as f:
        json.dump(case, f)
    script = PS_DRIVER.format(module=MODULE.replace("'", "''"),
                              casefile=casefile.replace("'", "''"),
                              outfile=outfile.replace("'", "''"))
    p = subprocess.run([pwsh(), "-NoProfile", "-NonInteractive", "-Command", script],
                       capture_output=True, text=True)
    if p.returncode == 3:
        return None, 3
    if p.returncode != 0:
        raise SystemExit(f"pwsh exited {p.returncode}:\n{p.stdout}\n{p.stderr}")
    with open(outfile, "rb") as f:
        return f.read(), 0


def powershell_rule(lab):
    print("\n  the netplan document — PowerShell, through New-NetplanDocument")
    for n, (name, case, want) in enumerate(CASES):
        got, _ = powershell_render(lab, case, n)
        if not check(got == want.encode("utf-8"), name):
            show_diff(want.encode("utf-8"), got)

    _, code = powershell_render(lab, REFUSAL, 999)
    check(code == 3, "Method None refuses to render a document")
    return True


# ---------------------------------------------------------------------------
# 2. The rule, in C# — through `os7-setup --netplan-render`
# ---------------------------------------------------------------------------

def csharp_render(argv, case):
    pairs = [f"{k}={v}" for k, v in case.items()]
    p = subprocess.run(list(argv) + ["--netplan-render"] + pairs, capture_output=True)
    return p.stdout, p.returncode, p.stderr.decode("utf-8", "replace")


def csharp_rule(argv):
    print("\n  the netplan document — C#, through os7-setup --netplan-render")
    try:
        got, code, err = csharp_render(argv, CASES[0][1])
    except OSError as e:
        print(f"      NOTE  NOT CHECKED. Could not run os7-setup: {e}")
        print("      NOTE  os7-setup is a Linux binary. --docker <image> runs it in a container.")
        return False
    if code != 0:
        # An old binary predates the flag and says "unknown option". That is a
        # missing check, not a failing one, and calling it a failure would train
        # whoever sees it to ignore this file.
        if "unknown option" in err:
            print("      NOTE  NOT CHECKED. This os7-setup predates --netplan-render.")
            print("      NOTE  Rebuild it with the container one-liner in this file's header.")
            return False
        check(False, "os7-setup --netplan-render exited 0", f"{code}: {err.strip()}")
        return True

    for name, case, want in CASES:
        got, code, err = csharp_render(argv, case)
        if code != 0:
            check(False, name, f"exited {code}: {err.strip()}")
            continue
        if not check(got == want.encode("utf-8"), name):
            show_diff(want.encode("utf-8"), got)

    _, code, _ = csharp_render(argv, REFUSAL)
    check(code == 3, "Method None refuses to render a document")
    return True


def find_setup(explicit):
    for candidate in (explicit, os.environ.get("OS7_SETUP"),
                      os.path.join(REPO, "out", "os7-setup-x64"),
                      os.path.join(REPO, "out", "os7-setup")):
        if candidate and os.path.isfile(candidate):
            return candidate
    return None


def setup_argv(setup, image):
    """How to invoke os7-setup: directly, or through a container.

    The container route is not a convenience. os7-setup is a Linux binary and
    this repository is developed from a Mac and a Windows box, so without it the
    C# half is unrunnable on the machine where the renderer is usually being
    edited — and a check that reports NOT CHECKED for ever is how one
    specification quietly becomes two.
    """
    if not image:
        return [setup]
    rel = os.path.relpath(os.path.abspath(setup), REPO).replace(os.sep, "/")
    if rel.startswith(".."):
        sys.exit(f"--docker needs an os7-setup inside the repository; {setup} is not.")
    argv = ["docker", "run", "--rm"]
    # Only when the tag says so. Passing --platform unconditionally would force
    # emulation on a host that already matches the image.
    tag = image.rsplit(":", 1)[-1]
    if tag in ("amd64", "arm64"):
        argv += ["--platform", f"linux/{tag}"]
    return argv + ["-v", f"{REPO}:/work", image, f"/work/{rel}"]


def main():
    ap = argparse.ArgumentParser(description="the netplan document, both languages")
    ap.add_argument("--setup", help="a runnable os7-setup, for the C# half")
    ap.add_argument("--docker", metavar="IMAGE",
                    help="run os7-setup in this image (e.g. os7-build:amd64), for a "
                         "host that cannot execute a Linux binary")
    args = ap.parse_args()

    print("### the netplan document (docs/POWERSHELL-SURFACE-PLAN.md P3)")
    print(f"### {len(CASES)} cases, plus the refusal")
    lab = tempfile.mkdtemp(prefix="os7-netplan-rule-")
    ran = []
    try:
        powershell_rule(lab)
        ran.append("PowerShell")

        setup = find_setup(args.setup)
        if setup:
            if csharp_rule(setup_argv(setup, args.docker)):
                ran.append("C#")
        else:
            print("\n  the netplan document — C#")
            print("      NOTE  NOT CHECKED. No os7-setup was found.")
            print("      NOTE  Pass --setup <path>, or set OS7_SETUP, or drop one in out/.")
        if "C#" not in ran:
            print("      NOTE  Build one with the container one-liner in this file's header,")
            print("      NOTE  then either run this on Linux or add --docker os7-build:<arch>.")
    finally:
        if os.environ.get("NETPLAN_RULE_KEEP"):
            print(f"\n(kept: {lab})")
        else:
            shutil.rmtree(lab, ignore_errors=True)

    print()
    if FAILS:
        print(f"{len(FAILS)} check(s) FAILED")
        return 1
    print(f"all checks passed — {', '.join(ran)} produce the same bytes for the same cases.")
    # Name what actually ran. "Both agree" and "the one that could run is right"
    # are different claims, and only one of them is earned in a given run.
    missing = [n for n in ("PowerShell", "C#") if n not in ran]
    if missing:
        print(f"NOT COMPARED IN THIS RUN: {', '.join(missing)}. The document has two "
              f"implementations and this run exercised {len(ran)}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
