#!/usr/bin/env python3
"""
Every OS/7 cmdlet, typed into a booted machine, with what came back.

docs/POWERSHELL-REFERENCE.md lists 194 functions and was generated by asking
the MODULES — `Get-Command` and `Get-Help` on a build host. That answers "does
this function exist and what does its synopsis say". It does not answer the
question an operator has, which is *what happens when I type it on a machine*:
whether it returns anything, whether it throws, whether it needs root, whether
it needs arguments nobody documented, whether it takes a minute.

Until now 47 of them had ever been typed at an installed machine, by
`shoot-manual.py`, and those 47 were chosen to illustrate the manual rather
than to cover the surface. This types all of them and records the answer.

    ./run-surface.py manual                 stage 1: the read-only verbs
    ./run-surface.py manual --stage write   stage 2: the ones that change things
    ./run-surface.py manual --stage all

Stage 1 is Get- and Test-: nothing it runs can change the machine, so it runs
in one pass on a live bench.

Stage 2 is everything else, and it REQUIRES a snapshot rather than taking one:
`os7lab.py snapshot` needs the VM stopped, and stopping it mid-survey would
cost a boot per group. So the bench must carry a snapshot before stage 2
starts, this refuses to run without one, and restoring afterwards is the
caller's move -- one `restore` after the pass, not one per cmdlet.

    ./os7lab.py down b && ./os7lab.py snapshot b pre-surface && ./os7lab.py up b
    ./run-surface.py b --stage write
    ./os7lab.py down b && ./os7lab.py restore b pre-surface

That is a weaker guarantee than a restore between every group, and it is the
honest one: a Set- that breaks the machine will make the cmdlets after it fail
for a reason that is not their own, and the matrix says so by listing them in
the order they ran.

WHAT THIS PRODUCES, AND WHAT IT IS FOR

    docs/SURFACE-MATRIX.md         one row per function: outcome, timing, size
    .vm/<bench>/surface/<Name>.txt exactly what the machine printed

The matrix is a MEASUREMENT, not a test: `empty` and `needs-root` are outcomes,
not failures, and the interesting rows are the ones a person would not have
predicted. It is deliberately not a pass/fail gate — a gate that went red
because a cmdlet correctly reported "no domain joined" would be a gate nobody
reads.

IT RUNS OVER SSH, and that is a choice with a cost. The serial line is what
proves a machine works with nothing but a kernel; ssh presupposes network,
sshd, PAM and an account. Here the exit code is worth more than the
independence: 194 invocations through a PSReadLine-repainted 80x24 console is
how a survey turns into a fortnight. Whether the machine has ssh at all is
`os7lab.py login`'s problem, and it is answered before this starts.
"""
import argparse
import json
import os
import re
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import os7lab                                                        # noqa: E402
from os7lab import Bench, run_remote, ssh_alive                      # noqa: E402

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MATRIX = os.path.join(REPO, "docs", "SURFACE-MATRIX.md")

MODULES = ("OS7", "Zfs", "Net", "Time", "Systemd", "Directory")

# Stage 1 is defined by VERB, not by a list of names, so a function added to
# the product joins the survey without anyone remembering to add it.
READ_VERBS = ("Get", "Test")

# What never runs unattended, whatever its verb, and why. Not a convenience
# list -- each of these would hang a survey or destroy the bench it runs on.
SKIP = {
    "Enter-PSSession":         "interactive by definition",
    "Enter-OS7AdminSession":   "prompts for a credential",
    "Exit-OS7AdminSession":    "only meaningful after Enter-",
    "Wait-OS7Update":          "blocks until an update finishes",
    "Update-OS7":              "installs a release; run-s5.py update is where that is measured",
    "Restore-OS7":             "reboots into another boot environment",
    "Join-OS7Domain":          "needs a domain controller and a credential",
    "Reset-OS7":               "destroys the machine",
    "Restart-OS7Computer":     "takes the bench down",
}

# Arguments for the functions that cannot be called bare. Every one of these is
# a REAL value on the bench machine rather than a placeholder, so the recorded
# output is output and not an error message about a missing parameter.
ARGS = {
    "Get-ZpoolStatus":            "rpool",
    "Get-ZfsSpace":               "rpool",
    "Get-ZpoolProperty":          "rpool",
    "Get-ZfsProperty":            "-Name rpool -Property compression",
    "Get-ZfsSnapshot":            "-Dataset rpool",
    "Test-Zpool":                 "rpool",
    "Get-OS7Service":             "-OS7Only",
    "Get-OS7Log":                 "-OS7Only -Tail 5",
    "Get-OS7BackupStatus":        "-SkipTargets",
    "Get-SystemdUnit":            "ssh.service",
    "Get-SystemdUnitProperty":    "-Name ssh.service -Property ActiveState",
    "Get-NetAdapterConfiguration": "",
    "Resolve-DnsNameQuery":       "-Name localhost",
    "Test-NetConnectionPort":     "-ComputerName 127.0.0.1 -Port 22",
}

# Seconds. Most answer instantly; the ones that talk to a network or to ZFS do
# not, and a survey that hangs on one of them has measured nothing.
TIMEOUT = 90


def inventory(b):
    """What the MACHINE says it has -- not what the reference file says.

    The reference is generated on a build host from the source tree. This asks
    the installed system, so a module that did not reach the image, or reached
    it half-populated (the os7-module .deb once carried two of five), shows up
    as a shorter list rather than as 194 failures.
    """
    script = (
        "$ErrorActionPreference='SilentlyContinue';"
        "foreach ($m in '" + "','".join(MODULES) + "') { Import-Module $m }"
        ";Get-Command -Module " + ",".join(MODULES) +
        " -CommandType Function,Cmdlet |"
        " Select-Object Name,Verb,Noun,@{n='Module';e={$_.ModuleName}} |"
        " ConvertTo-Json -Depth 3")
    rc, out, err = run_remote(b, script, elevated=True, timeout=180)
    body = out[out.find("["):] if "[" in out else out
    try:
        data = json.loads(body)
    except ValueError:
        raise SystemExit("could not read an inventory from the machine "
                         "(rc=%d):\n%s\n%s" % (rc, out[-800:], err[-800:]))
    if isinstance(data, dict):
        data = [data]
    return sorted(data, key=lambda d: d.get("Name") or "")


def classify(rc, out, err):
    """What the outcome WAS. Not pass/fail -- five outcomes, because the
    difference between them is the whole value of the survey."""
    text = (out or "") + "\n" + (err or "")
    low = text.lower()
    # "Cannot process command because of one or more missing mandatory
    # parameters" is PowerShell's wording under -NonInteractive, and it is the
    # one this survey meets most: without it, every Directory cmdlet that
    # needs a session reads as `error` and the matrix says the directory
    # surface is broken when what it is, is unasked.
    if re.search(r"missing an argument|cannot be found.*parameter|"
                 r"missing mandatory parameters|"
                 r"supply values for the following parameters", low):
        return "needs-args"
    if re.search(r"access to the path .* is denied|permission denied|"
                 r"must be run as root|requires elevation", low):
        return "needs-root"
    # A cmdlet that REFUSES for a stated reason is not a broken cmdlet, and
    # lumping it in with the ones that throw makes the matrix say the AD
    # surface is broken when what it is, is unasked. These are the product's
    # own sentences, quoted from the machine.
    if re.search(r"no directory session|no release index for channel", low):
        return "refused"
    # RC IS THE VERDICT WHEN IT IS ZERO. Test-OS7Network exits 0 and reports
    # `DnsWorks: False, DnsDetail: ... Exception ...` -- doing exactly its job,
    # which is to relay a failure it found. The first version of this matched
    # the word "exception" anywhere and called that cmdlet broken: a diagnostic
    # failing the thing it was diagnosing for saying the word.
    if rc == 0:
        return "ok" if out.strip() else "empty"
    if not out.strip() and not err.strip():
        return "empty"
    return "error"


def run_one(b, name, sudo=True):
    args = ARGS.get(name, "")
    script = (name + " " + args).strip()
    # Format-List over the raw object: a survey wants what the cmdlet HAS, and
    # the default table view drops columns silently once a type has more than
    # four properties -- which is the one thing a reader of this matrix would
    # never notice was missing.
    script = "$ErrorActionPreference='Continue'; " + script + " | Format-List *"
    t0 = time.time()
    try:
        rc, out, err = run_remote(b, script, elevated=sudo, timeout=TIMEOUT)
    except Exception as exc:                                   # noqa: BLE001
        return {"name": name, "outcome": "timeout", "seconds": time.time() - t0,
                "out": "", "err": str(exc), "script": script}
    # PowerShell serialises remote errors as CLIXML on stderr. Unwrapped here
    # so the transcript holds the message a person would read, not the XML.
    err = re.sub(r"#< CLIXML.*?<Objs[^>]*>", "", err, flags=re.S)
    err = re.sub(r"</?[A-Za-z][^>]*>", "", err)
    err = err.replace("_x001B_", "\x1b").replace("_x000A_", "\n")
    err = os7lab.strip_escapes(err).strip()
    return {"name": name, "outcome": classify(rc, out, err),
            "seconds": time.time() - t0, "rc": rc,
            "out": os7lab.strip_escapes(out).strip(), "err": err,
            "script": script}


def save(b, res):
    d = os.path.join(b.dir, "surface")
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, res["name"] + ".txt"), "w", encoding="utf-8") as f:
        f.write("# " + res["script"] + "\n")
        f.write("# outcome: %s   rc: %s   %.1fs\n\n"
                % (res["outcome"], res.get("rc"), res["seconds"]))
        if res["out"]:
            f.write(res["out"] + "\n")
        if res["err"]:
            f.write("\n--- stderr ---\n" + res["err"] + "\n")


def write_matrix(b, results, inv, stage):
    by_module = {}
    for r in results:
        by_module.setdefault(r.get("module") or "?", []).append(r)
    counts = {}
    for r in results:
        counts[r["outcome"]] = counts.get(r["outcome"], 0) + 1

    # LF explicitly: this file lives in docs/ and must not change its line
    # endings depending on which host generated it (shoot-manual.py carries
    # the same note, for the same reason).
    with open(MATRIX, "w", encoding="utf-8", newline="\n") as f:
        f.write("# Every cmdlet, typed at a booted machine\n\n")
        f.write("Generated by `installer/testing/run-surface.py` against bench "
                "`%s` (%s), %s.\n\n" % (b.name, b.arch.arch,
                                        time.strftime("%Y-%m-%d %H:%M")))
        f.write("This is a **measurement, not a gate**. `empty`, `needs-root` "
                "and `needs-args` are\noutcomes a correct cmdlet can have; what "
                "the table is for is the row nobody\nwould have predicted. The "
                "machine reported **%d** functions across %d modules;\nstage "
                "`%s` ran %d of them.\n\n"
                % (len(inv), len(by_module), stage, len(results)))
        f.write("| outcome | n | means |\n|---|---|---|\n")
        for k, why in (("ok", "returned something"),
                       ("refused", "declined for a stated reason"),
                       ("empty", "ran, returned nothing"),
                       ("needs-root", "refused without elevation"),
                       ("needs-args", "has a mandatory parameter"),
                       ("error", "threw, or exited non-zero"),
                       ("timeout", "did not finish in %ds" % TIMEOUT)):
            if counts.get(k):
                f.write("| `%s` | %d | %s |\n" % (k, counts[k], why))
        f.write("\nFull output per function: `.vm/%s/surface/<Name>.txt`\n\n"
                % b.name)
        for mod in sorted(by_module):
            f.write("\n## %s\n\n" % mod)
            f.write("| function | outcome | s | first line of what it printed |\n")
            f.write("|---|---|---|---|\n")
            for r in sorted(by_module[mod], key=lambda x: x["name"]):
                first = ""
                for line in (r["out"] or r["err"]).splitlines():
                    if line.strip():
                        first = line.strip()[:70]
                        break
                first = first.replace("|", "\\|")
                f.write("| `%s` | %s | %.1f | %s |\n"
                        % (r["name"], r["outcome"], r["seconds"], first))
    print("\n    matrix   " + MATRIX)


def main():
    p = argparse.ArgumentParser(description="Type every OS/7 cmdlet at a booted machine.")
    p.add_argument("name", help="bench name")
    p.add_argument("--stage", default="read", choices=("read", "write", "all"))
    p.add_argument("--only", help="regex: run just the functions matching it")
    p.add_argument("--no-sudo", action="store_true",
                   help="run unelevated, to see what an ordinary account gets")
    a = p.parse_args()

    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass

    b = Bench(a.name)
    b.require_running()
    if not ssh_alive(b):
        raise SystemExit("bench %s does not answer over ssh -- ./os7lab.py login %s"
                         % (a.name, a.name))

    print("### asking the machine what it has")
    inv = inventory(b)
    print("    %d functions in %d modules"
          % (len(inv), len({d.get("Module") for d in inv})))

    todo = []
    for d in inv:
        name, verb = d.get("Name"), d.get("Verb")
        if name in SKIP:
            continue
        if a.only and not re.search(a.only, name):
            continue
        is_read = verb in READ_VERBS
        if a.stage == "read" and not is_read:
            continue
        if a.stage == "write" and is_read:
            continue
        todo.append(d)

    print("### stage %s: %d functions\n" % (a.stage, len(todo)))
    if a.stage in ("write", "all"):
        # REFUSED, not warned about. A warning printed above 117 changing
        # cmdlets is one nobody can act on by the time they have read it.
        tags = os7lab.snapshot_tags(b)
        if not tags:
            raise SystemExit(
                "stage %r changes the machine and this bench has nothing to go "
                "back to.\n  ./os7lab.py down %s && ./os7lab.py snapshot %s "
                "pre-surface && ./os7lab.py up %s" % (a.stage, a.name, a.name, a.name))
        print("    note  stage %r changes the machine; snapshots to return to: %s\n"
              % (a.stage, ", ".join(tags)))

    results = []
    for i, d in enumerate(todo, 1):
        name = d.get("Name")
        r = run_one(b, name, sudo=not a.no_sudo)
        r["module"] = d.get("Module") or "?"
        save(b, r)
        results.append(r)
        first = ""
        for line in (r["out"] or r["err"]).splitlines():
            if line.strip():
                first = line.strip()[:46]
                break
        print("    %3d/%d  %-34s %-11s %5.1fs  %s"
              % (i, len(todo), name, r["outcome"], r["seconds"], first), flush=True)

    write_matrix(b, results, inv, a.stage)
    for k in ("error", "timeout"):
        bad = [r["name"] for r in results if r["outcome"] == k]
        if bad:
            print("    %-8s %s" % (k, ", ".join(bad)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
