using System.Text.Json;
using System.Text.Json.Serialization;
using OS7.Setup.Diagnostics;

namespace OS7.Setup.Model;

/// <summary>
/// Which OS/7 this is — read from the release manifest the build wrote.
///
/// docs/RELEASE-AND-UPDATE-PLAN.md §3.4. The manifest at
/// <see cref="Path"/> is generated by build hook 0090 from
/// build/config/os7-release.conf and is the single source of the version
/// number. Setup does not compose one, does not carry a constant, and does not
/// read /etc/os-release — the manifest is the machine-readable form and the one
/// `New-OS7BootEnvironmentName` already reads, so Setup's title bar and the name
/// of the boot environment it creates cannot disagree.
///
/// WHY THIS IS NOT A COMPILED-IN CONSTANT. A version baked into the binary is
/// correct exactly once, at the moment it is compiled. The binary is published
/// into an image whose package set is fixed later, and the same binary is what
/// a future upgrade path would run against an ALREADY INSTALLED system whose
/// version is a different number entirely. A constant would be right for the
/// medium and wrong for the target, and nothing would say which one it meant.
/// </summary>
internal sealed class Release
{
    public const string Path = "/usr/lib/os7/release.json";

    /// <summary>Four fields, §3.3. "0.0.0.0" when there is no manifest.</summary>
    public string Version { get; }

    /// <summary>stable | preview | development.</summary>
    public string Channel { get; }

    /// <summary>The archive snapshot the base came from, or null.</summary>
    public string? ArchiveSnapshot { get; }

    /// <summary>The Ubuntu release under it, e.g. "26.04".</summary>
    public string? BaseRelease { get; }

    /// <summary>
    /// False when the build could not identify its own source — a dirty tree,
    /// or no git checkout at all. Surfaced rather than swallowed: the whole
    /// argument for pinning the archive is that the number names a state, and a
    /// number that cannot do that has to say so where somebody will see it.
    /// </summary>
    public bool Reproducible { get; }

    /// <summary>
    /// True when the manifest was actually found. False means every field above
    /// is a placeholder — which happens when os7-setup is run outside an OS/7
    /// image, and is the honest answer rather than a plausible-looking number.
    /// </summary>
    public bool Known { get; }

    private Release(string version, string channel, string? snapshot,
                    string? baseRelease, bool reproducible, bool known)
    {
        Version = version;
        Channel = channel;
        ArchiveSnapshot = snapshot;
        BaseRelease = baseRelease;
        Reproducible = reproducible;
        Known = known;
    }

    /// <summary>What no manifest looks like. Deliberately not a plausible number.</summary>
    public static readonly Release Unknown =
        new("0.0.0.0", "unknown", null, null, false, false);

    private static Release? _current;

    /// <summary>
    /// The release this medium is. Read once — the file cannot change under a
    /// running Setup, and re-reading it per frame would put a syscall in the
    /// draw loop for no benefit.
    /// </summary>
    public static Release Current => _current ??= Load(Path);

    /// <summary>
    /// Read a manifest from anywhere. The path is a parameter and not baked in
    /// because the SAME reader has to answer two different questions:
    ///
    ///   "what is on this medium"      -> /usr/lib/os7/release.json
    ///   "what is on that disk"        -> /target/usr/lib/os7/release.json
    ///
    /// The second is what an upgrade needs in order to say what it would replace
    /// (SETUP-PLAN §3, screen 1's R=Repair), and it is the same file in the same
    /// format on a filesystem Setup has mounted. Writing the reader for one path
    /// and generalising later would mean writing it twice.
    /// </summary>
    public static Release Load(string path)
    {
        try
        {
            if (!File.Exists(path)) return Unknown;
            ReleaseManifest? m = JsonSerializer.Deserialize(
                File.ReadAllText(path), ReleaseJson.Default.ReleaseManifest);
            if (m?.Version is null or "") return Unknown;

            return new Release(
                m.Version,
                string.IsNullOrEmpty(m.Channel) ? "unknown" : m.Channel,
                m.Base?.ArchiveSnapshot,
                m.Base?.Release,
                m.Reproducible,
                known: true);
        }
        catch (Exception ex)
        {
            // A malformed manifest must not stop an install. It is metadata:
            // losing it costs a line on a screen, and refusing to run over it
            // would turn a cosmetic problem into an unbootable machine.
            Log.Warn($"could not read the release manifest at {path}: {ex.Message}");
            return Unknown;
        }
    }

    /// <summary>
    /// The first three fields of <see cref="Version"/> — "1.0.0" out of
    /// "1.0.0.95". docs/IDENTITY-PLAN.md §5.
    ///
    /// It is DERIVED and never stored: there is one version number, in one pin
    /// file, and a second stored form is how two numbers start disagreeing.
    ///
    /// A version with fewer than four fields comes back unchanged rather than
    /// padded. Nothing should ever produce one — build.sh composes four — but a
    /// manifest is a file and a display rule must not throw on a file.
    /// </summary>
    public string FriendlyVersion
    {
        get
        {
            string[] fields = Version.Split('.');
            return fields.Length <= 3 ? Version : string.Join('.', fields, 0, 3);
        }
    }

    /// <summary>
    /// What a person is shown: "1.0.0", or "1.0.0 (development)" when the
    /// channel is not stable — a preview build mistaken for a released one is
    /// the whole reason the channel field exists.
    ///
    /// THREE FIELDS, since 2026-08-26 (IDENTITY-PLAN I6). The rule is one
    /// question: does the number IDENTIFY a thing or DESCRIBE one? Chrome
    /// somebody reads in passing describes, so it gets three; anything that has
    /// to tell two builds apart identifies, and gets <see cref="Full"/>.
    ///
    /// One property per form, because the places that show a version differ
    /// only in what they put in front of it, and a formatter per call site
    /// would be a chance per call site to disagree about the same number.
    /// </summary>
    public string Short =>
        !Known                ? "unknown"
        : Channel is "stable" ? FriendlyVersion
                              : $"{FriendlyVersion} ({Channel})";

    /// <summary>
    /// All four fields: "1.0.0.95", or "1.0.0.95 (development)". For everywhere
    /// the number identifies rather than describes — an explicit query, the
    /// record of what was installed, a menu that exists to choose between two
    /// builds.
    /// </summary>
    public string Full =>
        !Known                ? "unknown"
        : Channel is "stable" ? Version
                              : $"{Version} ({Channel})";

    /// <summary>For the title row on every screen. Chrome, so friendly.</summary>
    public string TitleBar => $"Version {Short}";

    /// <summary>"OS/7 1.0.0 (development)", for a body line.</summary>
    public string Display =>
        Known ? $"OS/7 {Short}" : "OS/7 (no release manifest on this medium)";

    /// <summary>
    /// "OS/7 1.0.0.95 (development)". The Welcome screen, the Complete screen
    /// and `--version` use this one: the first two are the screens somebody
    /// photographs for a ticket, and the third is somebody asking.
    /// </summary>
    public string DisplayFull =>
        Known ? $"OS/7 {Full}" : "OS/7 (no release manifest on this medium)";

    /// <summary>
    /// A release that exists only to have the display rule applied to it, for
    /// `--version-rule`. Not for anything that installs: it has no archive, no
    /// base and no provenance, because the rule does not read any of them.
    /// </summary>
    internal static Release ForRule(string version, string channel) =>
        new(version, channel, null, null, reproducible: true, known: true);
}

/// <summary>
/// The wire shape of release.json. Only the fields Setup uses — the manifest is
/// a bill of materials and most of it is for `Get-OS7Version -Detailed`, not for
/// an installer.
///
/// Every name is spelled out with [JsonPropertyName] rather than left to a
/// naming policy: the file is written by python in build hook 0090 and uses
/// snake_case for compound keys, so a camelCase policy would silently match some
/// fields and not others.
/// </summary>
internal sealed class ReleaseManifest
{
    [JsonPropertyName("version")]      public string? Version { get; set; }
    [JsonPropertyName("channel")]      public string? Channel { get; set; }
    [JsonPropertyName("built")]        public string? Built { get; set; }
    [JsonPropertyName("architecture")] public string? Architecture { get; set; }

    /// <summary>Absent in an older manifest, and absent means "cannot say".</summary>
    [JsonPropertyName("reproducible")] public bool Reproducible { get; set; }

    [JsonPropertyName("base")]         public ReleaseBase? Base { get; set; }
}

internal sealed class ReleaseBase
{
    [JsonPropertyName("release")]          public string? Release { get; set; }
    [JsonPropertyName("codename")]         public string? Codename { get; set; }
    [JsonPropertyName("archive_snapshot")] public string? ArchiveSnapshot { get; set; }
}

/// <summary>
/// Source-generated, for the same reason PlanJson is: NativeAOT trims the
/// reflection serialiser away and it would throw at run time (spike S2).
/// </summary>
[JsonSourceGenerationOptions(AllowTrailingCommas = true,
                             ReadCommentHandling = JsonCommentHandling.Skip)]
[JsonSerializable(typeof(ReleaseManifest))]
internal partial class ReleaseJson : JsonSerializerContext;
