#!/usr/bin/env python3
"""
The manual's diagrams — one geometry, two languages.

Every picture here is drawn from facts that live somewhere else in this
repository, and the docstring of each function says where. Nothing is invented
for the drawing: a box that names a dataset names one the installer creates, a
box that names a file names one the build writes.

Two SVGs per diagram, `-de` and `-en`, from one layout and a label table. That
is deliberate rather than lazy — a translated diagram that was redrawn by hand
is a second drawing, and the two drift.

    python docs/manual/make-diagrams.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "images")

# The OS/7 palette, from build/lib/palette.py's decided values.
BLUE = "#0057ad"        # the Setup field
STRIPE = "#1289ff"      # the title stripe
INK = "#14181d"
MUTED = "#5a6570"
LINE = "#c4ccd4"
PAPER = "#ffffff"
TINT = "#eef4fb"
WARM = "#fdf3e3"
WARMLINE = "#e0b968"
GREEN = "#1f7a4d"
TINTG = "#e9f5ee"

FONT = "Segoe UI, Calibri, system-ui, sans-serif"
MONO = "Cascadia Mono, Consolas, monospace"


def svg(w, h, body):
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {0} {1}" '
        'width="{0}" height="{1}" font-family="{2}">'
        '<rect width="{0}" height="{1}" fill="{3}"/>{4}</svg>'
    ).format(w, h, FONT, PAPER, body)


def box(x, y, w, h, fill=PAPER, stroke=LINE, rx=6, sw=1.2, dash=None):
    d = ' stroke-dasharray="{0}"'.format(dash) if dash else ""
    return ('<rect x="{0}" y="{1}" width="{2}" height="{3}" rx="{4}" fill="{5}" '
            'stroke="{6}" stroke-width="{7}"{8}/>').format(x, y, w, h, rx, fill, stroke, sw, d)


def text(x, y, s, size=13, fill=INK, weight="400", anchor="start", font=None, ls="0"):
    return ('<text x="{0}" y="{1}" font-size="{2}" fill="{3}" font-weight="{4}" '
            'text-anchor="{5}" font-family="{6}" letter-spacing="{7}">{8}</text>').format(
        x, y, size, fill, weight, anchor, font or FONT, ls, esc(s))


def esc(s):
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def arrow(x1, y1, x2, y2, colour=BLUE, sw=1.6, dash=None):
    d = ' stroke-dasharray="{0}"'.format(dash) if dash else ""
    return ('<line x1="{0}" y1="{1}" x2="{2}" y2="{3}" stroke="{4}" stroke-width="{5}" '
            'marker-end="url(#a)"{6}/>').format(x1, y1, x2, y2, colour, sw, d)


DEFS = ('<defs><marker id="a" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" '
        'markerHeight="6" orient="auto"><path d="M0,0 L10,5 L0,10 z" fill="' + BLUE
        + '"/></marker></defs>')


# ---------------------------------------------------------------------------
# 1. The module layers.
#
# docs/POWERSHELL-SURFACE-PLAN.md P1/P2 and docs/POWERSHELL-REFERENCE.md: five
# generic modules that know their subsystem and nothing about OS/7, and one
# product module on top of them. The counts are the reference file's, which was
# generated by asking the modules.
# ---------------------------------------------------------------------------
def diagram_layers(L):
    b = [DEFS]
    W = 900
    b.append(box(40, 30, 820, 74, TINT, BLUE, 8, 2))
    b.append(text(60, 62, "powershell/OS7", 19, BLUE, "600", font=MONO))
    b.append(text(60, 86, L["product_layer"], 12.5, MUTED))
    b.append(text(840, 66, "95", 26, BLUE, "700", anchor="end"))

    mods = [("Zfs", "26", L["m_zfs"]), ("Net", "11", L["m_net"]),
            ("Time", "9", L["m_time"]), ("Systemd", "8", L["m_systemd"]),
            ("Directory", "36", L["m_dir"])]
    x = 40
    w = 156
    for name, n, desc in mods:
        b.append(box(x, 152, w, 92, PAPER, LINE, 6, 1.2))
        b.append(text(x + 12, 178, name, 15, INK, "600", font=MONO))
        b.append(text(x + w - 12, 178, n, 15, MUTED, "600", anchor="end"))
        for i, line in enumerate(wrap(desc, 21)):
            b.append(text(x + 12, 200 + i * 14, line, 10.5, MUTED))
        b.append(arrow(x + w / 2, 152, x + w / 2, 108))
        x += w + 10

    b.append(box(40, 286, 820, 62, "#f5f7fa", LINE, 6, 1.2))
    b.append(text(60, 314, "zfs · zpool · ip · netplan · chronyc · systemctl · journalctl · adcli · ldap",
                  12.5, MUTED, font=MONO))
    b.append(text(60, 336, L["os_layer"], 11, MUTED))
    x = 40
    for name, n, desc in mods:
        b.append(arrow(x + w / 2, 286, x + w / 2, 248))
        x += w + 10

    b.append(text(40, 376, L["layer_rule"], 11.5, INK))
    b.append(text(40, 394, "installer/testing/check-layering.py", 11.5, BLUE, font=MONO))
    return svg(W, 410, "".join(b))


def wrap(s, n):
    out, line = [], ""
    for word in s.split():
        if len(line) + len(word) + 1 > n:
            out.append(line)
            line = word
        else:
            line = (line + " " + word).strip()
    if line:
        out.append(line)
    return out[:3]


# ---------------------------------------------------------------------------
# 2. The disk.
#
# installer/SETUP-PLAN.md §4.4 — the partition table and the dataset hierarchy,
# copied from the drawing there rather than from memory. The one property the
# picture exists to make obvious is that USERDATA and DATA sit outside ROOT.
# ---------------------------------------------------------------------------
def diagram_disk(L):
    b = [DEFS]
    W, H = 900, 470
    b.append(text(40, 34, L["d_disk"], 14, INK, "600"))

    parts = [("p1", "512 MB", "FAT32", "/boot/efi", 150, WARM, WARMLINE),
             ("p2", "2 GB", "ZFS", "bpool", 150, WARM, WARMLINE),
             ("p3", L["d_rest"], "LUKS2", "rpool", 500, TINT, BLUE)]
    x = 40
    for tag, size, fs, name, w, fill, stroke in parts:
        b.append(box(x, 50, w, 66, fill, stroke, 5, 1.4))
        b.append(text(x + 10, 72, tag + "  " + size, 11.5, MUTED))
        b.append(text(x + 10, 92, fs, 13, INK, "600", font=MONO))
        b.append(text(x + 10, 108, name, 11, MUTED, font=MONO))
        x += w + 10
    b.append(text(40, 134, L["d_unenc"], 10.5, MUTED))
    b.append(text(360, 134, L["d_enc"], 10.5, BLUE, "600"))

    # ROOT — inside the boot environment
    b.append(box(40, 160, 400, 176, TINT, BLUE, 6, 1.6))
    b.append(text(56, 186, "rpool/ROOT/os7_<id>", 13.5, BLUE, "600", font=MONO))
    b.append(text(56, 204, L["d_in_be"], 11, MUTED))
    rows = ["/            " + L["d_system"],
            "/var/lib/dpkg  " + L["d_pkgdb"],
            "/var/lib/apt",
            "/var/cache"]
    for i, r in enumerate(rows):
        b.append(text(66, 228 + i * 20, r, 11, INK, font=MONO))
    b.append(box(40, 348, 400, 44, WARM, WARMLINE, 6, 1.4))
    b.append(text(56, 368, "bpool/BOOT/os7_<id>  ->  /boot", 12, INK, font=MONO))
    b.append(text(56, 384, L["d_bpool"], 10.5, MUTED))

    # Outside ROOT
    b.append(box(470, 160, 390, 232, TINTG, GREEN, 6, 1.6))
    b.append(text(486, 186, "rpool/USERDATA · rpool/DATA", 13.5, GREEN, "600", font=MONO))
    b.append(text(486, 204, L["d_out_be"], 11, MUTED))
    rows = ["USERDATA/<user>_<uuid>   /home/<user>",
            "USERDATA/root_<uuid>     /root",
            "DATA/log                 /var/log",
            "DATA/spool  DATA/tmp     /var/spool",
            "DATA/srv                 /srv",
            "DATA/lib/<service>       /var/lib/<s>",
            "DATA/snapd               /var/lib/snapd"]
    for i, r in enumerate(rows):
        b.append(text(496, 228 + i * 20, r, 10.5, INK, font=MONO))

    b.append(text(40, 424, L["d_rule_1"], 12, INK, "600"))
    for i, line in enumerate(wrap(L["d_rule_2"], 118)):
        b.append(text(40, 444 + i * 16, line, 11, MUTED))
    return svg(W, H, "".join(b))


# ---------------------------------------------------------------------------
# 3. Boot environments and rollback.
#
# docs/SESSION-BOOT-ENVIRONMENTS.md: three files decide what a machine boots,
# and none of them is a ZFS property. The picture is that sentence.
# ---------------------------------------------------------------------------
def diagram_be(L):
    b = [DEFS]
    W, H = 900, 400
    steps = [(L["be_s1"], "Get-OS7BootEnvironment"),
             (L["be_s2"], "Update-OS7"),
             (L["be_s3"], "Set-OS7BootEnvironment"),
             (L["be_s4"], "Restore-OS7")]
    x = 40
    w = 196
    for i, (title, cmd) in enumerate(steps):
        b.append(box(x, 40, w, 96, TINT if i % 2 == 0 else PAPER, BLUE, 6, 1.4))
        for j, line in enumerate(wrap(title, 24)):
            b.append(text(x + 12, 66 + j * 15, line, 11.5, INK, "600"))
        b.append(text(x + 12, 122, cmd, 10.5, BLUE, font=MONO))
        if i < 3:
            b.append(arrow(x + w, 88, x + w + 8, 88))
        x += w + 10

    b.append(text(40, 180, L["be_three"], 13, INK, "600"))
    facts = [("/etc/grub.d/09_os7-boot-environments", L["be_f1"]),
             ("EFI: set prefix=($root)/BOOT/<be>@/grub", L["be_f2"]),
             ("grubenv: saved_entry=<entry>", L["be_f3"])]
    y = 200
    for path, why in facts:
        b.append(box(40, y, 820, 50, PAPER, LINE, 5, 1.2))
        b.append(text(56, y + 22, path, 11.5, BLUE, "600", font=MONO))
        b.append(text(56, y + 40, why, 10.5, MUTED))
        y += 58

    b.append(box(40, 378, 820, 0, PAPER, PAPER))
    return svg(W, y + 6, "".join(b))


# ---------------------------------------------------------------------------
# 4. The update sequence.
#
# docs/RELEASE-AND-UPDATE-PLAN.md §4.2 as CURATION-AND-DELIVERY-PLAN §9 (C10)
# corrects it, which is the order Update-OS7 actually performs.
# ---------------------------------------------------------------------------
def diagram_update(L):
    b = [DEFS]
    W = 900
    steps = [L["u1"], L["u2"], L["u3"], L["u4"], L["u5"], L["u6"], L["u7"], L["u8"]]
    y = 44
    b.append(text(40, 28, L["u_title"], 13.5, INK, "600"))
    for i, s in enumerate(steps):
        b.append(box(40, y, 700, 38, TINT if i in (0, 7) else PAPER, BLUE if i in (0, 7) else LINE,
                     5, 1.4 if i in (0, 7) else 1.1))
        b.append(text(58, y + 24, str(i + 1), 12, BLUE, "700", font=MONO))
        b.append(text(84, y + 24, s, 12, INK))
        if i < len(steps) - 1:
            b.append(arrow(70, y + 38, 70, y + 46, BLUE, 1.3))
        y += 46
    b.append(box(760, 44, 100, y - 52, TINTG, GREEN, 6, 1.4))
    for i, line in enumerate(wrap(L["u_side"], 13)):
        b.append(text(772, 74 + i * 16, line, 10.5, GREEN, "600"))
    b.append(text(40, y + 22, L["u_note"], 11, MUTED))
    return svg(W, y + 40, "".join(b))


# ---------------------------------------------------------------------------
# 5. Backup.
#
# docs/BACKUP-PLAN.md: sanoid takes and thins snapshots, syncoid replicates,
# and OS/7 verifies by asking ZFS on both ends — never either tool.
# ---------------------------------------------------------------------------
def diagram_backup(L):
    b = [DEFS]
    W, H = 900, 340
    b.append(box(40, 40, 330, 200, TINT, BLUE, 6, 1.5))
    b.append(text(58, 66, L["b_source"], 13, BLUE, "600"))
    b.append(text(58, 90, "rpool/USERDATA/<user>", 11, INK, font=MONO))
    b.append(text(58, 108, "rpool/DATA/...", 11, INK, font=MONO))
    b.append(box(58, 126, 294, 44, PAPER, LINE, 5, 1.1))
    b.append(text(72, 146, "sanoid", 12, INK, "600", font=MONO))
    b.append(text(72, 162, L["b_sanoid"], 10.5, MUTED))
    b.append(box(58, 180, 294, 44, PAPER, LINE, 5, 1.1))
    b.append(text(72, 200, "syncoid", 12, INK, "600", font=MONO))
    b.append(text(72, 216, L["b_syncoid"], 10.5, MUTED))

    b.append(box(530, 40, 330, 200, TINTG, GREEN, 6, 1.5))
    b.append(text(548, 66, L["b_target"], 13, GREEN, "600"))
    b.append(text(548, 90, "Get-/New-OS7BackupTarget", 11, INK, font=MONO))
    b.append(text(548, 116, L["b_t1"], 11, MUTED))
    b.append(text(548, 136, L["b_t2"], 11, MUTED))
    b.append(text(548, 156, L["b_t3"], 11, MUTED))

    b.append(arrow(370, 140, 528, 140, BLUE, 2))
    b.append(text(450, 130, "zfs send", 11, BLUE, "600", anchor="middle", font=MONO))

    b.append(box(40, 264, 820, 56, WARM, WARMLINE, 6, 1.4))
    b.append(text(58, 288, "Get-OS7BackupStatus", 12.5, INK, "600", font=MONO))
    b.append(text(58, 308, L["b_status"], 11, MUTED))
    b.append(arrow(200, 264, 200, 244, BLUE, 1.4))
    b.append(arrow(700, 264, 700, 244, BLUE, 1.4))
    return svg(W, H, "".join(b))


# ---------------------------------------------------------------------------
# 6. Active Directory — the two stages.
#
# docs/AD-PLAN.md §2. The left half needs no domain membership and no new
# package; the right half is a machine account and sssd.
# ---------------------------------------------------------------------------
def diagram_ad(L):
    b = [DEFS]
    W, H = 900, 330
    b.append(box(40, 40, 400, 230, TINT, BLUE, 6, 1.5))
    b.append(text(58, 68, L["ad_s1"], 14, BLUE, "600"))
    b.append(text(58, 90, L["ad_s1_sub"], 11, MUTED))
    b.append(text(58, 122, "Enter-OS7AdminSession", 12, INK, "600", font=MONO))
    b.append(text(58, 142, "Get-OS7ADUser · New-OS7ADUser", 11, INK, font=MONO))
    b.append(text(58, 160, "Add-OS7ADGroupMember · Search-OS7AD", 11, INK, font=MONO))
    for i, line in enumerate(wrap(L["ad_s1_note"], 46)):
        b.append(text(58, 194 + i * 16, line, 10.5, MUTED))
    b.append(text(58, 254, "LDAPS 636", 11.5, BLUE, "600", font=MONO))

    b.append(box(460, 40, 400, 230, PAPER, MUTED, 6, 1.5, dash="5 4"))
    b.append(text(478, 68, L["ad_s2"], 14, INK, "600"))
    b.append(text(478, 90, L["ad_s2_sub"], 11, MUTED))
    b.append(text(478, 122, "Join-OS7Domain", 12, INK, "600", font=MONO))
    b.append(text(478, 142, "Get-/Set-OS7DomainLogonPolicy", 11, INK, font=MONO))
    b.append(text(478, 160, "Test-OS7Domain · Repair-OS7Domain", 11, INK, font=MONO))
    for i, line in enumerate(wrap(L["ad_s2_note"], 46)):
        b.append(text(478, 194 + i * 16, line, 10.5, MUTED))
    b.append(text(478, 254, "adcli · sssd · Kerberos", 11.5, MUTED, "600", font=MONO))

    b.append(text(40, 306, L["ad_rule"], 11.5, INK))
    return svg(W, H, "".join(b))


# ---------------------------------------------------------------------------
# 7. The management plane.
#
# docs/CURATION-AND-DELIVERY-PLAN.md C8/C8a and the OS7.Management surface:
# three separate paths, three separate answers, one cmdlet that asks all three.
# ---------------------------------------------------------------------------
def diagram_management(L):
    b = [DEFS]
    W, H = 900, 300
    cards = [("Entra ID", "Get-OS7EntraStatus", L["mg_entra"], "authd · brokers.d"),
             ("Intune", "Get-OS7IntuneEnrollment", L["mg_intune"], "intune-portal"),
             ("Azure Arc", "Get-OS7ArcStatus", L["mg_arc"], "azcmagent")]
    x = 40
    w = 266
    for title, cmd, desc, pkg in cards:
        b.append(box(x, 70, w, 150, PAPER, BLUE, 6, 1.4))
        b.append(text(x + 16, 100, title, 15, BLUE, "600"))
        b.append(text(x + 16, 122, cmd, 11, INK, font=MONO))
        for i, line in enumerate(wrap(desc, 34)):
            b.append(text(x + 16, 150 + i * 15, line, 10.5, MUTED))
        b.append(text(x + 16, 206, pkg, 10.5, MUTED, font=MONO))
        b.append(arrow(x + w / 2, 70, x + w / 2, 56, BLUE, 1.4))
        x += w + 11

    b.append(box(40, 20, 820, 36, TINT, BLUE, 5, 1.5))
    b.append(text(56, 44, "Get-OS7ManagementStatus", 13, BLUE, "600", font=MONO))
    b.append(text(300, 44, L["mg_one"], 11.5, MUTED))

    b.append(text(40, 254, L["mg_note"], 11.5, INK))
    for i, line in enumerate(wrap(L["mg_note2"], 118)):
        b.append(text(40, 274 + i * 16, line, 11, MUTED))
    return svg(W, H, "".join(b))


DE = {
    "product_layer": "Die Produktschicht: kennt OS/7 — Bootumgebungen, Releases, Richtlinien",
    "m_zfs": "Pools, Datasets, Snapshots",
    "m_net": "ip, netplan, resolved",
    "m_time": "chrony, Zeitzone",
    "m_systemd": "Units, Journal",
    "m_dir": "LDAP, Kerberos, Realm",
    "os_layer": "Die Werkzeuge des Betriebssystems — nur die generischen Module rufen sie auf",
    "layer_rule": "Die Produktschicht darf ein Subsystem nicht direkt erreichen. Geprüft, nicht behauptet:",
    "d_disk": "Datenträger — installer/SETUP-PLAN.md §4.4",
    "d_rest": "Rest",
    "d_unenc": "unverschlüsselt — von Intune ignoriert",
    "d_enc": "verschlüsselt (LUKS2 unter ZFS, Entscheidung D3)",
    "d_in_be": "IN der Bootumgebung — rollt bei Restore-OS7 mit zurück",
    "d_system": "das System selbst",
    "d_pkgdb": "die Paketdatenbank",
    "d_bpool": "der Kernel und das initramfs dieser Bootumgebung",
    "d_out_be": "AUSSERHALB — überlebt jeden Rollback",
    "d_rule_1": "Die Regel, die jeden Pfad entscheidet:",
    "d_rule_2": "Ein Pfad gehört in die Bootumgebung genau dann, wenn ein Rollback ihn korrekter macht. "
                "Zustand, den etwas außerhalb dieser Maschine ebenfalls kennt, bleibt draußen — die "
                "Gegenseite rollt nicht zurück.",
    "be_s1": "Bootumgebungen ansehen",
    "be_s2": "Neue anlegen und befüllen",
    "be_s3": "Aktiv schalten und neu starten",
    "be_s4": "Zurückrollen, wenn es schiefging",
    "be_three": "Drei Dinge entscheiden, was die Maschine startet — und keines davon ist eine ZFS-Eigenschaft:",
    "be_f1": "OS/7 schreibt sein eigenes Menü: ein Eintrag je Bootumgebung",
    "be_f2": "Eine Datei auf der EFI-Partition sagt, wessen Menü GRUB überhaupt liest",
    "be_f3": "Und saved_entry benennt den Eintrag darin",
    "u_title": "Update-OS7 — die Reihenfolge, die tatsächlich ausgeführt wird",
    "u1": "Das Paar aus rpool/ROOT und bpool/BOOT klonen",
    "u2": "Den Klon zusammensetzen und einhängen",
    "u3": "apt im Klon auf beide Repositories zeigen lassen",
    "u4": "apt install os7-<mode>=<version>  ->  full-upgrade  ->  autoremove",
    "u5": "Die Migrationen des Releases ausführen (chroot-Phase)",
    "u6": "initramfs neu bauen, Menü neu erzeugen",
    "u7": "Die neue Bootumgebung aktiv schalten",
    "u8": "Nach dem Neustart: firstboot-Migrationen, alte Umgebungen aufräumen",
    "u_side": "Die laufende Umgebung wird nie verändert",
    "u_note": "Schlägt ein Schritt fehl, bleibt die laufende Umgebung die aktive. Es gibt nichts zurückzunehmen.",
    "b_source": "Quelle — diese Maschine",
    "b_sanoid": "nimmt Snapshots und dünnt sie aus",
    "b_syncoid": "repliziert per zfs send/receive",
    "b_target": "Ziel — Pool oder SSH-Gegenstelle",
    "b_t1": "lokaler Pool auf einer externen Platte,",
    "b_t2": "oder ein Pool auf einem anderen Rechner",
    "b_t3": "per SSH",
    "b_status": "fragt ZFS auf beiden Seiten und vergleicht Snapshot-GUIDs — niemals sanoid, "
                "denn dessen Erfolgsmeldung ist kein Beweis",
    "ad_s1": "Verwalten",
    "ad_s1_sub": "Kein Domänenbeitritt. Kein Computerkonto. Kein neues Paket.",
    "ad_s1_note": "Ein Administrator meldet sich VON dieser Maschine aus mit dem eigenen "
                  "AD-Konto an und arbeitet als er selbst.",
    "ad_s2": "Mitglied werden",
    "ad_s2_sub": "Die Maschine bekommt ein Computerkonto in der Domäne.",
    "ad_s2_note": "Damit können sich Domänenbenutzer an dieser Maschine anmelden. "
                  "Setzt adcli und sssd voraus.",
    "ad_rule": "Die beiden sind unabhängig: Verwalten funktioniert ohne Mitgliedschaft, "
               "Mitgliedschaft ohne Verwaltungssitzung.",
    "mg_entra": "Kann sich ein Benutzer mit einem Entra-Konto an dieser Maschine anmelden?",
    "mg_intune": "Ist diese Maschine bei Intune registriert und meldet sie sich?",
    "mg_arc": "Ist der Azure-Connected-Machine-Agent installiert und verbunden?",
    "mg_one": "beantwortet alle drei in einem Aufruf",
    "mg_note": "Drei getrennte Wege, drei getrennte Antworten.",
    "mg_note2": "Jedes dieser Cmdlets sagt auch, WARUM etwas nicht geht, statt nur \"nein\" — "
                "ein fehlender Broker sieht sonst aus wie ein falsches Kennwort.",
}

EN = {
    "product_layer": "The product layer: it knows OS/7 — boot environments, releases, policy",
    "m_zfs": "Pools, datasets, snapshots",
    "m_net": "ip, netplan, resolved",
    "m_time": "chrony, time zone",
    "m_systemd": "Units, the journal",
    "m_dir": "LDAP, Kerberos, realms",
    "os_layer": "The operating system's own tools — only the generic modules call them",
    "layer_rule": "The product layer may not reach a subsystem directly. Checked, not asserted:",
    "d_disk": "The disk — installer/SETUP-PLAN.md §4.4",
    "d_rest": "rest",
    "d_unenc": "unencrypted — Intune ignores it",
    "d_enc": "encrypted (LUKS2 under ZFS, decision D3)",
    "d_in_be": "INSIDE the boot environment — Restore-OS7 rolls it back",
    "d_system": "the system itself",
    "d_pkgdb": "the package database",
    "d_bpool": "this environment's kernel and initramfs",
    "d_out_be": "OUTSIDE — survives every rollback",
    "d_rule_1": "The rule that decides each path:",
    "d_rule_2": "A path belongs inside the boot environment if, and only if, rolling it back makes "
                "the system more correct. State that something outside this machine also believes "
                "stays outside — the other side does not roll back.",
    "be_s1": "Look at what is there",
    "be_s2": "Create a new one and fill it",
    "be_s3": "Activate it and restart",
    "be_s4": "Roll back when it went wrong",
    "be_three": "Three things decide what the machine boots — and none of them is a ZFS property:",
    "be_f1": "OS/7 writes its own menu: one entry per boot environment",
    "be_f2": "A file on the EFI partition names whose menu GRUB reads at all",
    "be_f3": "And saved_entry names the entry within it",
    "u_title": "Update-OS7 — the order that is actually performed",
    "u1": "Clone the rpool/ROOT and bpool/BOOT pair",
    "u2": "Assemble the clone and mount it",
    "u3": "Point apt inside the clone at both repositories",
    "u4": "apt install os7-<mode>=<version>  ->  full-upgrade  ->  autoremove",
    "u5": "Run the release's migrations (the chroot phase)",
    "u6": "Rebuild the initramfs, regenerate the menu",
    "u7": "Activate the new boot environment",
    "u8": "After the restart: firstboot migrations, prune old environments",
    "u_side": "The running environment is never modified",
    "u_note": "If a step fails, the running environment is still the active one. There is nothing to undo.",
    "b_source": "Source — this machine",
    "b_sanoid": "takes snapshots and thins them",
    "b_syncoid": "replicates with zfs send/receive",
    "b_target": "Target — a pool or an SSH host",
    "b_t1": "a local pool on an external disk,",
    "b_t2": "or a pool on another machine",
    "b_t3": "over SSH",
    "b_status": "asks ZFS on both ends and compares snapshot GUIDs — never sanoid, whose "
                "success is not evidence",
    "ad_s1": "Administering",
    "ad_s1_sub": "No domain join. No computer account. No new package.",
    "ad_s1_note": "An administrator signs in to the directory FROM this machine with their own "
                  "AD account and works as themselves.",
    "ad_s2": "Becoming a member",
    "ad_s2_sub": "The machine gets a computer account in the domain.",
    "ad_s2_note": "That is what lets domain users log in to this machine. Needs adcli and sssd.",
    "ad_rule": "The two are independent: administering works without membership, membership "
               "without an admin session.",
    "mg_entra": "Can a user sign in to this machine with an Entra account?",
    "mg_intune": "Is this machine enrolled in Intune, and is it checking in?",
    "mg_arc": "Is the Azure Connected Machine agent installed and connected?",
    "mg_one": "answers all three in one call",
    "mg_note": "Three separate paths, three separate answers.",
    "mg_note2": "Each of these cmdlets also says WHY something does not work rather than just "
                "\"no\" — a missing broker otherwise looks exactly like a wrong password.",
}

DIAGRAMS = {
    "diagram-layers": diagram_layers,
    "diagram-disk": diagram_disk,
    "diagram-boot-environments": diagram_be,
    "diagram-update": diagram_update,
    "diagram-backup": diagram_backup,
    "diagram-active-directory": diagram_ad,
    "diagram-management": diagram_management,
}


def main():
    os.makedirs(OUT, exist_ok=True)
    for lang, labels in (("de", DE), ("en", EN)):
        for name, fn in DIAGRAMS.items():
            path = os.path.join(OUT, name + "-" + lang + ".svg")
            with open(path, "w", encoding="utf-8") as f:
                f.write(fn(labels))
            print("    " + os.path.basename(path))


if __name__ == "__main__":
    main()
