#!/usr/bin/env python3
"""
Appendix A — every command, generated by asking the modules.

docs/POWERSHELL-REFERENCE.md is generated the same way and for the same reason:
a reference that is typed by hand lists what somebody believed was there. This
one asks PowerShell for `Get-Command`, `Get-Help` and the real parameter
metadata, so a cmdlet that is missing from the appendix is missing from the
product, and one that is in it exists with the parameters printed beside it.

    python docs/manual/make-reference.py

Writes docs/manual/de/90-anhang-a-referenz.md and
       docs/manual/en/90-appendix-a-reference.md

The synopses come out of the modules and are English — they are the text
`Get-Help` returns on the machine. The German appendix therefore prints the
module's own sentence and translates the surrounding structure only; inventing
a German synopsis here would put a second, unchecked description beside the one
the machine gives an operator who types `Get-Help`.
"""
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))

MODULES = ["Zfs", "Net", "Time", "Systemd", "Directory", "OS7"]

COMMON = ("Verbose Debug ErrorAction WarningAction InformationAction ProgressAction "
          "ErrorVariable WarningVariable InformationVariable OutVariable OutBuffer "
          "PipelineVariable WhatIf Confirm").split()

PS = r"""
$ErrorActionPreference = 'Stop'
foreach ($m in @({quoted})) {{
    Import-Module (Join-Path '{repo}' "powershell/$m/$m.psd1") -Force -ErrorAction SilentlyContinue
}}
$common = @({common})
$out = foreach ($c in Get-Command -Module {modules} | Sort-Object ModuleName, Name) {{
    $h = Get-Help $c.Name -ErrorAction SilentlyContinue
    [pscustomobject]@{{
        Module   = $c.ModuleName
        Name     = $c.Name
        Verb     = $c.Verb
        Synopsis = ($h.Synopsis -replace '\s+', ' ').Trim()
        Params   = @(foreach ($p in $c.Parameters.Values) {{
            if ($p.Name -notin $common) {{
                [pscustomobject]@{{
                    Name      = $p.Name
                    Type      = $p.ParameterType.Name
                    Mandatory = [bool]($p.Attributes | Where-Object {{
                        $_ -is [System.Management.Automation.ParameterAttribute] -and $_.Mandatory }})
                }}
            }}
        }})
    }}
}}
$out | ConvertTo-Json -Depth 5 -Compress
"""


def ask_the_modules():
    script = PS.format(modules=",".join(MODULES),
                       quoted=",".join("'" + m + "'" for m in MODULES),
                       repo=REPO.replace("\\", "/"),
                       common=",".join("'" + c + "'" for c in COMMON))
    p = subprocess.run(["pwsh", "-NoProfile", "-Command", script],
                       capture_output=True, text=True)
    if p.returncode != 0:
        raise SystemExit("pwsh failed:\n" + p.stderr[:2000])
    return json.loads(p.stdout.lstrip("﻿"))


TEXT = {
    "de": {
        "file": "de/90-anhang-a-referenz.md",
        "title": "Anhang A  Alle Befehle",
        "intro": (
            "Diese Liste wurde **erzeugt, indem die Module gefragt wurden** — jeder Name, "
            "jede Beschreibung und jede Parameterliste stammt von `Get-Command` und "
            "`Get-Help` auf einer OS/7-Maschine. Was hier fehlt, gibt es nicht; was hier "
            "steht, existiert mit genau diesen Parametern.\n\n"
            "Die Beschreibungen sind die englischen Originaltexte der Module — es ist "
            "derselbe Satz, den `Get-Help <Befehl>` auf der Maschine ausgibt. Eine "
            "übersetzte Fassung an dieser Stelle wäre eine zweite Beschreibung neben der, "
            "die ein Administrator tatsächlich zu sehen bekommt."),
        "legend": ("**Pflichtparameter sind fett.** Ein Cmdlet mit mehreren Parametersätzen "
                   "hat mehrere Pflichtparameter, von denen jeweils nur einer gebraucht wird — "
                   "`Get-Help <Befehl>` zeigt die Sätze einzeln."),
        "modules": "Die sechs Module",
        "col_module": "Modul", "col_layer": "Schicht", "col_count": "Befehle",
        "generic": "generisch", "product": "das Produkt",
        "h_cmd": "Befehl", "h_syn": "Beschreibung", "h_par": "Parameter",
        "none": "keine",
        "layer_note": {
            "Zfs": "ZFS: Pools, Datasets, Snapshots. Kennt nichts von OS/7.",
            "Net": "Das Netzwerk: `ip`, netplan, networkd, NetworkManager, resolved.",
            "Time": "Die Uhr: chrony, Zeitzone, Hardware-Uhr.",
            "Systemd": "Units und das Journal.",
            "Directory": "LDAP, Kerberos und die Realm-Mitgliedschaft. Kennt nichts von "
                         "Active Directorys Richtlinien und nichts von OS/7.",
            "OS7": "Die Produktschicht: Bootumgebungen, Releases, Sicherung, Verwaltung, "
                   "Verzeichnis — alles, was OS/7-spezifisch ist.",
        },
    },
    "en": {
        "file": "en/90-appendix-a-reference.md",
        "title": "Appendix A  Every command",
        "intro": (
            "This list was **generated by asking the modules** — every name, every "
            "description and every parameter list comes from `Get-Command` and `Get-Help` "
            "on an OS/7 machine. What is missing here is missing from the product; what is "
            "here exists with exactly these parameters."),
        "legend": ("**Mandatory parameters are bold.** A cmdlet with several parameter sets "
                   "has several mandatory parameters, of which only one is needed at a time — "
                   "`Get-Help <command>` shows the sets separately."),
        "modules": "The six modules",
        "col_module": "Module", "col_layer": "Layer", "col_count": "Commands",
        "generic": "generic", "product": "the product",
        "h_cmd": "Command", "h_syn": "What it does", "h_par": "Parameters",
        "none": "none",
        "layer_note": {
            "Zfs": "ZFS: pools, datasets, snapshots. Knows nothing about OS/7.",
            "Net": "The network: `ip`, netplan, networkd, NetworkManager, resolved.",
            "Time": "The clock: chrony, the time zone, the hardware clock.",
            "Systemd": "Units and the journal.",
            "Directory": "LDAP, Kerberos and realm membership. Knows nothing about Active "
                         "Directory's policy and nothing about OS/7.",
            "OS7": "The product layer: boot environments, releases, backup, management, "
                   "the directory — everything that is OS/7-specific.",
        },
    },
}


def escape(s):
    return s.replace("|", "\\|")


def render(commands, lang):
    t = TEXT[lang]
    by_module = {}
    for c in commands:
        by_module.setdefault(c["Module"], []).append(c)

    out = ["# " + t["title"], "", t["intro"], "", t["legend"], "",
           "## " + t["modules"], "",
           "| " + t["col_module"] + " | " + t["col_layer"] + " | " + t["col_count"] + " |",
           "|---|---|---|"]
    for m in MODULES:
        layer = t["product"] if m == "OS7" else t["generic"]
        out.append("| `powershell/" + m + "/` | " + layer + " | "
                   + str(len(by_module.get(m, []))) + " |")
    out.append("")

    for m in MODULES:
        cmds = by_module.get(m, [])
        if not cmds:
            continue
        out += ["## `" + m + "`", "", t["layer_note"][m], "",
                "| " + t["h_cmd"] + " | " + t["h_syn"] + " | " + t["h_par"] + " |",
                "|---|---|---|"]
        for c in cmds:
            params = []
            for p in c["Params"]:
                params.append("**" + p["Name"] + "**" if p["Mandatory"] else p["Name"])
            out.append("| `" + c["Name"] + "` | " + escape(c["Synopsis"]) + " | "
                       + (", ".join(params) if params else "*" + t["none"] + "*") + " |")
        out.append("")
    return "\n".join(out) + "\n"


def main():
    commands = ask_the_modules()
    print("    " + str(len(commands)) + " commands, asked of the modules")
    for lang in ("de", "en"):
        path = os.path.join(HERE, TEXT[lang]["file"])
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(render(commands, lang))
        print("    " + TEXT[lang]["file"])


if __name__ == "__main__":
    sys.exit(main())
